namespace FastUnityCreationKit.Utility
{
    public static class Directories
    {
        public const string ROOT_PATH = "Assets/AutoGenerated";
        public const string DATABASES_PATH = "Databases";
        
        
        public const string STATUS_PATH = "Status";
    }
}